### ISSUE TITLE
Interactive debug

### ISSUE THREAD

**Issue by DamienCassou** [ecukes/ecukes#146]
Hi,

would it be possible to debug a feature in such a way that the tester sees what Emacs is doing while it is doing it? It would mean adding a short delay between the execution of each step and making the Emacs frame visible. It would only work for tests that exercise visible things (e.g., buffer manipulation). Currently, debugging failed feature tests is a hell.

**Comment by rejeep** [comment]
There is an old issue similar to this (see https://github.com/ecukes/ecukes/issues/8). Is this what you are after?

**Comment by DamienCassou** [comment]
That's exactly it. Thanks
