### ISSUE TITLE
Allow use of melpa stable by removing noflet dependency?

### ISSUE THREAD

**Issue by davidshepherd7** [ecukes/ecukes#147]
Currently ecukes cannot be installed from melpa stable alone due to the dependency on noflet. There's a [noflet issue](https://github.com/nicferrier/emacs-noflet/issues/15) which has been open for nearly 4 months asking for a melpa stable version but it hasn't happened. So unfortunately it seems unlikely to be resolved soon.

This problematic for me because it means I can't use the same package versions for testing as are used in reality: there seems to be an [unwritten melpa rule](https://github.com/milkypostman/melpa/pull/2870#issuecomment-113884608) requiring packages to only depend on melpa stable versions of packages. It has already led to a [bug in `electric-operator`](https://github.com/davidshepherd7/electric-operator/issues/9#issuecomment-116323408).

I know it's nasty, but could you directly include `noflet.el` into ecukes until noflet is in melpa stable? Or maybe find some other workaround?

If not I guess I'll try to hack around it by setting up Cask to pull noflet directly from the git repository.

**Comment by davidshepherd7** [comment]
PS: I'm happy to create a pull request/run tests/etc. if you tell me what you want to do about it.

**Comment by rejeep** [comment]
Ecukes does not depend on noflet, but Espuds does. See https://github.com/ecukes/espuds/blob/master/espuds.el#L74. If you want to, it's fine by me if you replace noflet with something else.
