### ISSUE TITLE
Multiple features per file quietly does the wrong thing

### ISSUE THREAD

**Issue by davidshepherd7** [ecukes/ecukes#148]
When I have a file containing multiple features, all the features get silently merged into a single feature. 

I know (now, after some googling)  that we shouldn't have more than one feature per file, but it would be nice if ecukes gave a warning or an error.

I'll have a go at implementing this now.

**Comment by davidshepherd7** [comment]
This is turning out to be harder than expected because the current parser doesn't seem to have any conception of strings.

**Comment by rejeep** [comment]
https://github.com/ecukes/ecukes/commit/c89a4e7286c7eb78398d4550b748a047bdac277a
