### ISSUE TITLE
Improve output on failing tests

### ISSUE THREAD

**Issue by expez** [ecukes/ecukes#150]
```
      Expected '(ns cljr.foo
        (:require [clj-time.core :as t]
                  [clojure.set :as st]))
      
      (defn use-time []
        (t/now)
        (st/difference #{:a :b} #{:a :c}))' to be part of '(ns cljr.foo
        (:require [clojure.string :as s]
                  [clojure.set :as st]
                  [clj-time.core :as t]))
      
      (defn use-time []
        (t/now)
        (st/difference #{:a :b} #{:a :c}))', but was not.
```

When a test fails in ecukes (especially when the difference is only in whitespace!) I often have to copy this stuff into emacs and use `ediff` on two different buffers to spot the problem.  It would be lovely if ecukes helped in spotting differences.

In the event that this is too much work, would it at least be possible change the formatting like so: 
```
      Expected:
   '(ns cljr.foo
        (:require [clj-time.core :as t]
                  [clojure.set :as st]))
      
      (defn use-time []
        (t/now)
        (st/difference #{:a :b} #{:a :c}))' 

to be part of:
   '(ns cljr.foo
        (:require [clojure.string :as s]
                  [clojure.set :as st]
                  [clj-time.core :as t]))
      
      (defn use-time []
        (t/now)
        (st/difference #{:a :b} #{:a :c}))', but was not.
```

When the expected and actual are aligned in this manner, visual diffing is a lot easier.

**Comment by rejeep** [comment]
It's actually Espuds that does this (see https://github.com/ecukes/espuds/blob/master/espuds.el#L394), not Ecukes. If you want to fix it in Espuds, that would be great, I kind of agree with you! :)
