### ISSUE TITLE
Newest version breaks our tests

### ISSUE THREAD

**Issue by magnars** [ecukes/ecukes#151]
The `ecukes-20150717.558` version recently built gives us just a halted Emacs with `Wrong type argument: number-or-marker-p, nil`. 

What can I do to help figure out what's going wrong?

Cask only lets us specify a *minimum* version for a dependency, so we're unable to downgrade properly. Any thoughts?

**Comment by magnars** [comment]
This is in Emacs 24.3.1 - apparently not an issue on 24.5.1.

**Comment by rejeep** [comment]
I just did a bad commit in Ecukes, but it's reverted now. Works if you update?

**Comment by magnars** [comment]
I'll let you know once melpa builds the new version. Thanks!

**Comment by magnars** [comment]
Latest build works again, thanks!

**Comment by rejeep** [comment]
Great, sorry for the noise. :)
