### ISSUE TITLE
Missing super-duper.el

### ISSUE THREAD

**Issue by shakthimaan** [ecukes/ecukes#152]
I am trying to follow the super-duple example from https://github.com/ecukes/ecukes#installation.

After running "cask exec ecukes new", it creates the necessary features/ folder and files in it. When I run ecukes, I get the following output:

```
$ cask exec ecukes

Cannot open load file: no such file or directory, super-duper
```

The output in the documentation for "ls super-duper" mentions a super-duper.el file, which I think I am missing. What should be its contents?

**Comment by shakthimaan** [comment]
I had to copy ecukes-project.el to super-duper.el in the top-level super-duper directory, and replace the last line with (provide 'super-duper)".

This is missing in the README.markdown file:

```
Copy ecukes-project.el to super-duper.el, replacing the last line with (provide 'super-duper).
```

**Comment by rejeep** [comment]
Good point, added better instructions, see https://github.com/ecukes/ecukes/commit/cb8d9eb90f922c2063129c147045da7f12e1f994
