### ISSUE TITLE
Debugger prints stack traces on error in emacs 25 even when --debug is not set

### ISSUE THREAD

**Issue by davidshepherd7** [ecukes/ecukes#156]
When a cl-assert fails the stack trace is printed regardless of the --debug flag.

I had a dig around and it looks like the debugger variable is still set correctly when the assertion fails. It also seems that the `ecukes-debug-callbacks` is (correctly) empty. But it still somehow prints the stack trace.

I'm pretty sure this started when I switched to emacs25, but I haven't gone back and tested it on emacs24 since then.

I can post more details if needed, but I think this will be easy to reproduce (I'm getting it in multiple unrelated projects).

For anyone else running into this: a work around that I'm using for now is to comment out the line `(setq debug-on-error t)` in `ecukes-cli.el` (and make sure you either re-byte-compile or delete the elc file so that the changes apply).

**Comment by rejeep** [comment]
I never use cl-assert so I haven't experienced this. Does this also affect `should` for example?

**Comment by davidshepherd7** [comment]
Pretty much all of the [espuds steps](https://github.com/ecukes/espuds/blob/master/espuds.el#L143) use it internally, which is why it's causing me problems (never used it directly myself).

**Comment by rejeep** [comment]
Ahh, didn't realise that I used it in Espuds.

Can you verify that it works in version 24? And also, are you using a prerelease of version 25 or is it from the master branch?

**Comment by davidshepherd7** [comment]
[Here](https://travis-ci.org/davidshepherd7/electric-operator/builds/155728398) is an example of the output on various versions. Both pretest and the current git snapshot have the issue, but 24.5 doesn't.

**Comment by rejeep** [comment]
Then I will close this as 25 is not released yet. If you want to dig into this yourself, I'd be happy to merge the fix. But until 25 has been released stable, I won't spend any time on it, sorry.

**Comment by davidshepherd7** [comment]
I had a dig through the release notes and couldn't see anything that seemed relevant, so yeah hopefully it's just a bug in the prerelease version.

**Comment by rejeep** [comment]
Yeah, hopefully. You could always create a bug report if you have the energy.

**Comment by davidshepherd7** [comment]
This should be [fixed](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24778) in 25.2.

**Comment by davidshepherd7** [comment]
There are still problems with this, see #159
