### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [ecukes/ecukes#164]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by tarsius** [comment]
Friendly ping! Sorry for being pushy, but it looks like rms is going to request that all unlicensed packages be removed from Melpa, and if I can demonstrate that authors are still acting in response to my requests such as this one, then he might delay that another few weeks, giving the remaining authors more time to act. I think it would be a mistake to remove the unlicensed packages as that has the potential of causing a lot of bad blood.

Thanks a lot!

**Comment by rejeep** [comment]
Sorry for not responding, but I'm totally AFK during the summer. If you open a PR with the changes, I can press the merge button, but I cant fix the code on my phone... 🙂

**Comment by davidshepherd7** [comment]
I can do the changes, I just didn't want to go ahead and change the license
when 99.99% of the code is yours.

I'll do it tomorrow night (busy until then).

**Comment by tarsius** [comment]
Thanks you too!

@rejeep There exist a few open pull requests in some of your repositories that I have opened. In most cases you did not respond so far. Or you went silent before merging or otherwise bringing the discussion to an end. I have sent you some pings but felt uneasy about doing so because I don't know whether you think my requests are silly and whether my reminders therefore annoy you. On the other hand I have some vague memory that you stopped using Emacs so you might have turned off notifications in your elisp repositories.

If my reminders were annoying, then please accept my apologies. Also sorry for hijacking this issue to bring up these unrelated pull requests. I do however have to try one last time to get these issues resolved.

Unless you disagree with the proposed changes, please merge them soon. Otherwise please briefly explain why you are reject the proposed changes. Then I at least know that they don't have a change and that I can stop trying to get them merged. Thanks a lot!

Here is a list of those pull requests:
- https://github.com/rejeep/ert-runner.el/pull/40
- https://github.com/rejeep/wrap-region.el/pull/31
- https://github.com/cask/cask/pull/386
- https://github.com/rejeep/commander.el/pull/10
- https://github.com/cask/epl/pull/34
- https://github.com/rejeep/git.el/pull/6
- https://github.com/rejeep/ruby-end.el/pull/16

**Comment by davidshepherd7** [comment]
All done :+1:

**Comment by tarsius** [comment]
Thanks!

**Comment by rejeep** [comment]
I don't do that much coding these days and when I do I split my time between Emacs and Atom. I always go dark on my vacay, that's why I've not been responding. I will take a look at the PS above.

**Comment by tarsius** [comment]
Thanks for doing it now Johan! And sorry for being so pushy!

**Comment by tarsius** [comment]
One of the pull requests was unfortunately missing from the above list. Please also look at https://github.com/rejeep/drag-stuff.el/pull/24.

**Comment by rejeep** [comment]
No worries, push away! 🙂

**Comment by tarsius** [comment]
I think that's it :wink: :wine_glass:
