### ISSUE TITLE
Issue in Travis

### ISSUE THREAD

**Issue by Ergus** [ecukes/ecukes#178]
Hi I use ecukes in travis:
```
Scenario: C-w to kill line
    When I insert:
      """
        1. line
        2. line
        3. line
      """
    And I place the cursor after "2."
    And I press "C-w l"
    Then I should see:
      """
        1. line
        3. line
      """
```

But I get this messages I can't debug (I am VERY new using ecukes)
```
 Scenario: C-w to kill line
    When I insert:
      """
        1. line
        2. line
        3. line
      """
      Wrong number of arguments: #[(contents) c\207" [contents] 1], 2
    And I place the cursor after "2."
    And I press "C-w l"
    Then I should see:
      """
        1. line
        3. line
      """
```
Could you please tell me whats going on?

In the local machine the test just stops after the first message.

**Comment by dickmao** [comment]
I would try `cask exec ecukes --debug` to get a backtrace.

**Comment by notake** [comment]
I have the same problem when using latest ecukes in travis. https://travis-ci.org/clojure-emacs/clj-refactor.el/builds/561912771
I think this problem was probably caused by this commit: https://github.com/ecukes/ecukes/commit/52f33faf6944bdf1fcdb1b930d22f4137a11fef7#diff-3e7a1be289e3ee00d985af787efea746R99

**Comment by Ergus** [comment]
> I would try `cask exec ecukes --debug` to get a backtrace.

I did before reporting the issue, but I the execution just stocks when arrives that point. No report,  no information. And when `C-c'  it just stops with a dumb message. WHen I gdb the core file I just says that emacs received a kill signal but nothing else.

**Comment by dickmao** [comment]
I broke pystring steps in #177 .  Sorry.

I reverted the change in #179.
