### ISSUE TITLE
Pre defines steps

### ISSUE THREAD

**Issue by hatheroldev** [ecukes/ecukes#181]
I really struggle to find a list of pre-defines step definitions.

IMHO those should be documented...

And I would love to have a way to spot their definition in source, so I can dig for undocumented steps and or inspect how they where implemented.

**Comment by rejeep** [comment]
Have you looked at https://github.com/ecukes/espuds?

**Comment by hatheroldev** [comment]
No, that's really what I searched. Thanks for that hint.

Carfully reading the documentation helps.
