### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by doublep** [ecukes/ecukes#183]
Latest stable release is four years old and doesn't include later fixes. Since there are many tagged releases, people might expect that MELPA Stable is up-to-date for the package.

**Comment by dickmao** [comment]
You and I appear to be the only people looking at this repo.  I don't use ecukes anymore, and I suspect you don't either.

**Comment by davidshepherd7** [comment]
:wave: FYI I still use it for some of my older emacs lisp projects :slightly_smiling_face:

**Comment by doublep** [comment]
> and I suspect you don't either

I don't, but I have a request (almost done) to add support for it to Eldev.

Thank you.
