### ISSUE TITLE
Setting a variable with a step

### ISSUE THREAD

**Issue by ddoherty03** [ecukes/ecukes#194]
This is more a question than an "issue", but maybe I'm missing something obvious.  I have a package (commify) that changes its behavior based on several custom variables, and I want to set up scenarios based on those settings.  Here is a step I wrote, but it doesn't seem to have any effect:
```
(When "^I set variable '\\([^\']+\\) to \"\\([^\"]+\\)\"$"
  (lambda (var val)
    (set (intern var) (eval (read val)))))
```
And I try to use it with:
```
  Background:
    Given I switch to buffer "*commify-test*"
    And I clear the buffer
    And I set variable 'commify-enable-hash to "nil"
```
Is this not correct?

**Comment by ddoherty03** [comment]
I am setting this up in emacs stack exchange, so you can close this if you don't like having a "help" question here.  If so, sorry for the noise.

**Comment by ddoherty03** [comment]
I noticed that this step is defined in espuds, but it does not seem to have an effect.  Is there possibly a scoping issue here, or is there a good way to test it?

**Comment by rejeep** [comment]
What's not working? See the tests for how to use it: https://github.com/ecukes/espuds/blob/fc558aca5a89f3298096ae15a9ccac46ef8bba13/test/espuds-test.el#L425-L441

**Comment by ddoherty03** [comment]
@rejeep, my bad.  I had a setup step that was counteracting this, so consider this closed.
